server:
  port: 9090
amazon:
  s3:
    accessKey: [accessKey]
    secretKey: [secretKey]
    bucket:
      name: bucket1
  region: us-west-2
localstack:
  enabled: true
  endpoint: http://localhost:4572
  region: us-east-1